/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcpchat;

/**
 *
 * @author Monkeybone
 */
public class ChatView extends javax.swing.JPanel {

    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        statusColor = new javax.swing.JPanel();
        statusText = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        statusColor.setBackground(new java.awt.Color(204, 0, 102));
        statusColor.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout statusColorLayout = new javax.swing.GroupLayout(statusColor);
        statusColor.setLayout(statusColorLayout);
        statusColorLayout.setHorizontalGroup(
            statusColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        statusColorLayout.setVerticalGroup(
            statusColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        add(statusColor, gridBagConstraints);

        statusText.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel3.setText("Disconnected");

        javax.swing.GroupLayout statusTextLayout = new javax.swing.GroupLayout(statusText);
        statusText.setLayout(statusTextLayout);
        statusTextLayout.setHorizontalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTextLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        statusTextLayout.setVerticalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        add(statusText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel statusColor;
    private javax.swing.JPanel statusText;
    // End of variables declaration//GEN-END:variables
}
