/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcpchat;

/**
 *
 * @author Monkeybone
 */
public class ChatView extends javax.swing.JPanel {

    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPanel = new javax.swing.JPanel();
        statusColor = new javax.swing.JPanel();
        statusText = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        statusPanel.setPreferredSize(new java.awt.Dimension(400, 20));
        statusPanel.setLayout(new java.awt.BorderLayout());

        statusColor.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout statusColorLayout = new javax.swing.GroupLayout(statusColor);
        statusColor.setLayout(statusColorLayout);
        statusColorLayout.setHorizontalGroup(
            statusColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        statusColorLayout.setVerticalGroup(
            statusColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        statusPanel.add(statusColor, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout statusTextLayout = new javax.swing.GroupLayout(statusText);
        statusText.setLayout(statusTextLayout);
        statusTextLayout.setHorizontalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        statusTextLayout.setVerticalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        statusPanel.add(statusText, java.awt.BorderLayout.EAST);

        add(statusPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel statusColor;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel statusText;
    // End of variables declaration//GEN-END:variables
}
